[project.urls]
Homepage = "https://github.com/kurrawong/ogc-metadata-conversion-lib#readme"
Documentation = "https://github.com/kurrawong/ogc-metadata-conversion-lib#readme"
Source = "https://github.com/kurrawong/ogc-metadata-conversion-lib"
Changelog = "https://github.com/Kurrawong/ogc-metadata-conversion-lib/releases"

[project]
name = "ocl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jamiefeiss", email = "jamie.feiss@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.5",
    "pydantic-xml>=2.18.0",
    "rich>=14.2.0",
    "typer>=0.20.0",
]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[project.scripts]
ocl = "ocl.cli:app"